um = int (input('digite um numero '))
dois = int (input('digite um numero '))
tres = int (input('digite um numero '))
quatro = int(input('digite um numero '))
big = max(um, dois, tres, quatro)
jonh = min(um, dois, tres, quatro)
cucas = ((um + dois + tres + quatro) / 4)
nagib = (big - jonh)
print (f'A média aritmética é: {cucas}')
print (f'A diferença entre o maior e o menor valor é: {nagib}')
